# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_bundle.ipynb.

# %% ../nbs/02_bundle.ipynb #4767bcd3
from __future__ import annotations
import hashlib, os, shutil, sys, zipfile
from fastcore.all import Path, first

# %% auto #0
__all__ = ['graft', 'link_duplicates', 'strip_zip', 'install_modern_icon', 'finish', 'frozen_distribution']

# %% ../nbs/02_bundle.ipynb #2b553810
def graft(app, name, python=None):
    "Put the installed `name` package into a built bundle."
    import importlib.util
    spec = importlib.util.find_spec(name)
    if spec is None or not spec.submodule_search_locations:
        raise SystemExit(f'cannot graft {name}: it is not installed here')
    src = Path(first(spec.submodule_search_locations))
    lib = _lib_dir(app)
    want = 'python%d.%d' % (python or sys.version_info[:2])
    if lib.name != want: raise SystemExit(f'cannot graft {name}: bundle is {lib.name}, this is {want}')
    dest = lib/name
    for stray in lib.glob(f'{name}.*'): stray.unlink()
    shutil.rmtree(dest, ignore_errors=True)
    shutil.copytree(src, dest, ignore=shutil.ignore_patterns('__pycache__', '*.pyc'))
    return dest.relative_to(app)

def _lib_dir(app):
    "The bundle's `lib/pythonX.Y`, on either platform's layout."
    app = Path(app)
    for base in (app/'Contents'/'Resources'/'lib', app/'lib', app):
        if (hit := first(sorted(base.glob('python3.*')))) is not None: return Path(hit)
    raise SystemExit(f'{app} has no lib/python3.* to write into')

# %% ../nbs/02_bundle.ipynb #f054e586
def link_duplicates(app, names, floor=1_000_000):
    "Hardlink duplicate package files and return megabytes saved."
    lib = _lib_dir(app)
    seen, saved = {}, 0
    for name in names:
        for f in sorted((lib/name).rglob('*')):
            if not f.is_file() or f.is_symlink() or f.stat().st_size < floor: continue
            key = (f.stat().st_size, hashlib.sha256(f.read_bytes()).hexdigest())
            if (other := seen.get(key)) is None: seen[key] = f; continue
            if os.stat(f).st_ino == os.stat(other).st_ino: continue
            saved += f.stat().st_size
            f.unlink(); os.link(other, f)
    return round(saved / 1e6)

# %% ../nbs/02_bundle.ipynb #9e0b3d82
def strip_zip(app, prefixes=()):
    "Remove matching entries from the bundle archive and return megabytes saved."
    z = first(sorted(_lib_dir(app).parent.glob('python3*.zip')))
    if not z or not prefixes: return 0
    prefixes = tuple(prefixes)
    keep, dropped = [], 0
    with zipfile.ZipFile(z) as src:
        for info in src.infolist():
            if info.filename.startswith(prefixes): dropped += info.compress_size; continue
            keep.append((info, src.read(info.filename)))
    if not dropped: return 0
    tmp = Path(str(z) + '.new')
    with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as out:
        for info, data in keep: out.writestr(info, data)
    tmp.replace(z)
    return round(dropped / 1e6)

# %% ../nbs/02_bundle.ipynb #22fd45d1
def install_modern_icon(app, icon, identity=None, deployment_target='14.0'):
    "Install an Icon Composer icon before signing, retaining the ICNS fallback."
    icon = Path(icon) if icon else None
    if icon is None or not icon.is_dir(): return None
    try: from iconmage import install_icon
    except ImportError:
        print('  iconmage not installed; keeping the ICNS icon alone '
              '(uv tool install git+https://github.com/AnswerDotAI/iconmage.git)')
        return None
    try: return install_icon(icon, app, deployment_target=deployment_target, identity=identity)
    except Exception as e:
        print(f'  Icon Composer icon not installed ({type(e).__name__}: {e}); keeping the ICNS one')
        return None

# %% ../nbs/02_bundle.ipynb #4f455d17
def finish(app, spec, identity=None):
    "Everything a bundle needs after the freezer wrote it, in the order it needs it."
    out = {}
    for name in spec.grafted: out[name] = str(graft(app, name))
    dropped = [*spec.unreachable, *[f'{n}/' for n in spec.grafted]]
    out['stripped_mb'] = strip_zip(app, dropped)
    out['linked_mb'] = link_duplicates(app, spec.grafted)
    out['modern_icon'] = bool(install_modern_icon(app, spec.modern_icon, identity))
    return out

# %% ../nbs/02_bundle.ipynb #8be45025
def frozen_distribution():
    "Return a setuptools distribution that ignores project dependencies."
    from setuptools.dist import Distribution
    class Frozen(Distribution):
        def parse_config_files(self, *args, **kwargs):
            super().parse_config_files(*args, **kwargs)
            self.install_requires = []
    return Frozen
