# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_menus.ipynb.

# %% ../nbs/06_menus.ipynb #11fab8fe
from __future__ import annotations
from dataclasses import dataclass

# %% auto #0
__all__ = ['MenuItem', 'Std', 'Js', 'Binding']

# %% ../nbs/06_menus.ipynb #1a54959d
@dataclass(frozen=True)
class MenuItem:
    "One action in a menu. A blank action is a separator."
    action: str = ''
    kind: str = ''
    def __post_init__(self):
        if self.kind not in ('', 'warn'):
            raise ValueError(f'{self.action or "separator"}: bad menu kind {self.kind!r}')

# %% ../nbs/06_menus.ipynb #d30dc4ea
@dataclass(frozen=True)
class Std:
    "A row AppKit implements itself. The selector goes to the responder chain, target nil."
    title: str
    selector: str
    key: str = ''
    mods: str = 'mod'

# %% ../nbs/06_menus.ipynb #86983e95
@dataclass(frozen=True)
class Js:
    "A row no action backs, named by the expression it runs."
    title: str
    expr: str

# %% ../nbs/06_menus.ipynb #191bfb64
@dataclass(frozen=True)
class Binding:
    "What a menu row reads from the host's keymap: the chords, the label, and where it applies."
    keys: tuple = ()
    label: str = ''
    scope: str = 'global'
    @property
    def bound(self): return bool(self.keys)
