# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_window.ipynb.

# %% ../nbs/04_window.ipynb #fefbb5f4
from __future__ import annotations

# %% auto #0
__all__ = ['APP_NAME', 'ENV_PREFIX', 'CFG', 'BACKENDS', 'DEFAULT_SIZE', 'MIN_SIZE', 'STORAGE', 'EAGER_CDP', 'SPLASH',
           'DOCK_RECENT', 'NO_SUBSTITUTION', 'WINDOW_KW', 'CMD', 'CTRL', 'ALT', 'SHIFT', 'use_app', 'errstr',
           'ShellApi', 'backend', 'shell_ready', 'wait_for_http', 'start_cdp', 'warm_cdp', 'window_size', 'splash',
           'dock_menu', 'quiet_text_substitution', 'keep_running_in_dock', 'shell_api', 'make_window',
           'off_main_thread', 'open_window', 'run_shell', 'menus', 'watch_open_events', 'mac_key', 'menu_chord',
           'menu_bar', 'eval_js', 'install_menu_patch']

# %% ../nbs/04_window.ipynb #0c685d46
import os, sys, threading, time

# %% ../nbs/04_window.ipynb #49187062
from fastcore.all import Path

# %% ../nbs/04_window.ipynb #d450e443
from fastcore.xdg import xdg_config_home

# %% ../nbs/04_window.ipynb #b119a172
from .menus import Binding, Js, MenuItem, Std

# %% ../nbs/04_window.ipynb #ffbc16b0
#: The host application kavacha is wearing: its name, its config directory and the prefix on the
#: environment variables it reads. `use_app` sets all three, and everything reads them when it runs
#: rather than at import, because a host calls `use_app` after importing this module.
APP_NAME = os.environ.get('KAVACHA_APP_NAME') or 'app'
ENV_PREFIX = 'KAVACHA_'

def use_app(name, cfg=None, env_prefix='KAVACHA_'):
    "Wear `name`: its config directory, its storage and its environment prefix."
    global APP_NAME, CFG, STORAGE, ENV_PREFIX, EAGER_CDP
    APP_NAME, ENV_PREFIX = str(name or 'app'), str(env_prefix or '')
    CFG = Path(cfg) if cfg else Path(os.environ.get(f'{ENV_PREFIX}CFG') or xdg_config_home()/APP_NAME)
    STORAGE, EAGER_CDP = CFG/'webview', f'{ENV_PREFIX}CDP_EAGER'
    return APP_NAME

# %% ../nbs/04_window.ipynb #ed752fec
CFG = Path(os.environ.get('KAVACHA_CFG') or xdg_config_home()/APP_NAME)

# %% ../nbs/04_window.ipynb #09644c1b
def errstr(e): return f"{type(e).__name__}: {e}"

# %% ../nbs/04_window.ipynb #d6740c65
BACKENDS = {'darwin': 'cocoa', 'win32': 'edgechromium', 'linux': 'gtk'}

# %% ../nbs/04_window.ipynb #eb657af2
DEFAULT_SIZE = (1440, 900)

# %% ../nbs/04_window.ipynb #b7aed37e
MIN_SIZE = (900, 560)

# %% ../nbs/04_window.ipynb #6fcef046
STORAGE = CFG/'webview'

# %% ../nbs/04_window.ipynb #9ef17b53
EAGER_CDP = 'KAVACHA_CDP_EAGER'   #: `use_app` re-spells this

# %% ../nbs/04_window.ipynb #747b2cb6
class ShellApi:
    "What the page may ask the native window for, as `window.pywebview.api.*`."
    #: Set by `run_shell`. Takes a folder and gives it a window of its own.
    on_open_folder = None
    def open_folder(self, path):
        "Open a folder in a window of its own. pywebview runs every `js_api` call on its own thread."
        if not path or self.on_open_folder is None: return False
        self.on_open_folder(str(path))
        return True
    def pick_folder(self):
        "The platform's own folder chooser. A path, or None if it was cancelled."
        import webview
        if (window := webview.active_window()) is None: return None
        try: picked = window.create_file_dialog(webview.FileDialog.FOLDER)
        except Exception as e:
            print(f'  folder dialog: {errstr(e)}')
            return None
        return str(picked[0]) if picked else None
    #: Set by `run_shell`. Gives the page the recent-folder list before the server is up.
    on_recent = None
    def recent(self):
        "Whatever the host offers as recent folders, or nothing."
        return list(self.on_recent()) if self.on_recent else []

# %% ../nbs/04_window.ipynb #fd3e4208
def backend(platform=None):
    "pywebview's GUI name for `platform`, or None where Leela has no supported webview."
    return BACKENDS.get(platform or sys.platform)

# %% ../nbs/04_window.ipynb #533b9552
def shell_ready(platform=None):
    "`(ok, why)`: whether a native window can be opened here, and what is missing if not."
    gui = backend(platform)
    if gui is None: return False, f'no native webview backend for {platform or sys.platform}'
    try: import webview  # noqa: F401
    except ImportError as e: return False, f'pywebview is not installed ({errstr(e)})'
    return True, gui

# %% ../nbs/04_window.ipynb #5ce28d0d
def wait_for_http(url, timeout=60, interval=.1):
    "Block until `url` answers, or `timeout` passes. True if the server came up."
    import urllib.request
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            urllib.request.urlopen(url, timeout=.5).close()
            return True
        except urllib.error.HTTPError: return True   # a 4xx proves the port is live
        except Exception: time.sleep(interval)
    return False

# %% ../nbs/04_window.ipynb #c3d0bac2
def start_cdp(port=9223, headless=True, wait=False, timeout=None, profile=None):
    "Bring up the persistent CDP Chrome the inline browser renders into, on a thread."
    def boot():
        try:
            from fossick.cdp import _debug_ready, cdp_setup
            from fossick.core import syncy
            if _debug_ready(port): return
            syncy(cdp_setup(port=port, headless=headless, timeout=timeout, user_data_dir=profile))
        except Exception as e: print(f'  inline browser unavailable: {errstr(e)}')
    t = threading.Thread(target=boot, daemon=True, name='kavacha-cdp-boot')
    t.start()
    if wait: t.join(timeout or 30)
    return t

# %% ../nbs/04_window.ipynb #061ae319
def warm_cdp(port=9223, profile=None):
    "Start Chrome at launch only if `$KAVACHA_CDP_EAGER` asks for it. See `docs/desktop.md`."
    if os.environ.get(EAGER_CDP, '').strip() not in ('1', 'true', 'yes'): return None
    return start_cdp(port, headless=True, profile=profile)

# %% ../nbs/04_window.ipynb #39d21b92
def window_size(spec=None):
    "`WIDTHxHEIGHT` from `spec` or `$<prefix>WINDOW_SIZE`, else the default. See `use_app`."
    spec = spec or os.environ.get(f'{ENV_PREFIX}WINDOW_SIZE', '')
    try:
        w, h = (int(n) for n in str(spec).lower().split('x', 1))
        if w >= MIN_SIZE[0] and h >= MIN_SIZE[1]: return w, h
    except (ValueError, TypeError): pass
    return DEFAULT_SIZE

# %% ../nbs/04_window.ipynb #97a7c39c
SPLASH = """<!doctype html><meta charset=utf-8><title>{name}</title>
<style>html,body{{height:100%;margin:0;background:#171b20;color:#f4f7f9;
font:15px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
display:flex;align-items:center;justify-content:center}}
div{{text-align:center;opacity:.85}}b{{display:block;font-size:34px;letter-spacing:-.02em;margin-bottom:10px}}
i{{font-style:normal;font-size:13px;opacity:.6}}</style>
<div><b>{name}</b><i style="{style}">{note}</i></div>"""

def splash(name=None, note='starting the workspace…', style=''):
    "The holding page a window shows before its URL answers, wearing the host's name."
    return SPLASH.format(name=name or APP_NAME, note=note, style=style)

# %% ../nbs/04_window.ipynb #ede581c5
def _unreachable(url):
    "The same splash, saying why nothing arrived."
    return splash(note=f'the workspace at {url} did not answer', style='color:#e06c75')

# %% ../nbs/04_window.ipynb #c9ba99ed
DOCK_RECENT = 8          #: rows on the Dock menu, which is a shortcut and not a file browser

# %% ../nbs/04_window.ipynb #3a4723da
_dock_target = None

# %% ../nbs/04_window.ipynb #6b10a2aa
def _recent_target(on_folder):
    "One for the life of the app: a menu holds no reference to a Python object, so this must."
    global _dock_target
    if _dock_target is None: _dock_target = _RecentTarget.alloc().init_with(on_folder)
    return _dock_target

# %% ../nbs/04_window.ipynb #299e331c
def dock_menu(on_folder, recent=None):
    "The Dock's own menu: the folders last open, newest first. `recent` is the host's list of paths."
    from AppKit import NSMenu, NSMenuItem
    rows = list(recent or ())[:DOCK_RECENT]
    menu = NSMenu.alloc().init()
    if not rows:
        menu.addItem_(_disabled('No recent folders'))
        return menu
    target = _recent_target(on_folder)
    for path in rows:
        path = str(path)
        item = NSMenuItem.alloc().initWithTitle_action_keyEquivalent_(
            os.path.basename(path.rstrip('/')) or path, b'openRecent:', '')
        item.setToolTip_(path)
        item.setRepresentedObject_(path)
        item.setTarget_(target)
        menu.addItem_(item)
    return menu

# %% ../nbs/04_window.ipynb #d5de3f3b
def _disabled(title):
    from AppKit import NSMenuItem
    item = NSMenuItem.alloc().initWithTitle_action_keyEquivalent_(title, None, '')
    item.setEnabled_(False)
    return item

# %% ../nbs/04_window.ipynb #928bfb4b
_hidden, _on_folder, _delegates, _on_recent = [], None, None, None

# %% ../nbs/04_window.ipynb #4903e49d
def _dock_delegates():
    "The two delegate subclasses. Built once: an Objective-C class name is global to the runtime."
    global _delegates
    if _delegates is not None: return _delegates
    from Foundation import NO, YES
    from webview.platforms.cocoa import BrowserView
    class Windows(BrowserView.WindowDelegate):
        def windowShouldClose_(self, window):
            window.orderOut_(None)
            if window in _hidden: _hidden.remove(window)
            _hidden.append(window)
            return NO
    class App(BrowserView.AppDelegate):
        def applicationShouldHandleReopen_hasVisibleWindows_(self, app, visible):
            if not visible and _hidden: _hidden.pop().makeKeyAndOrderFront_(None)
            return YES
        def applicationDockMenu_(self, app):
            try: return dock_menu(_on_folder, _on_recent() if _on_recent else None)
            except Exception as e: print(f'  dock menu: {errstr(e)}'); return None
    _delegates = (Windows, App)
    return _delegates

# %% ../nbs/04_window.ipynb #b48c51bb
#: What macOS rewrites as you type, and must not while you are typing code. WKWebView hands a
#: `contenteditable` to NSSpellChecker; a browser does not, which is why the packaged app turned
#: quotes into curly quotes and moved the caret out from under CodeMirror, and the served one
#: never did. Inline prediction is in the list because Tab is what accepts one, so the Tab that was
#: meant for the completion list went to the system instead and left the caret at the start of the
#: line. Written to this app's own defaults domain, so nothing outside it changes.
NO_SUBSTITUTION = ('NSAutomaticQuoteSubstitutionEnabled', 'NSAutomaticDashSubstitutionEnabled',
                   'NSAutomaticTextReplacementEnabled', 'NSAutomaticSpellingCorrectionEnabled',
                   'NSAutomaticPeriodSubstitutionEnabled', 'NSAutomaticCapitalizationEnabled',
                   'NSAutomaticInlinePredictionEnabled')

# %% ../nbs/04_window.ipynb #051b423e
def quiet_text_substitution():
    "Turn off the system's autocorrect for this app. True when it took."
    if sys.platform != 'darwin': return False
    try:
        from Foundation import NSUserDefaults
        d = NSUserDefaults.standardUserDefaults()
        for k in NO_SUBSTITUTION: d.setBool_forKey_(False, k)
        return True
    except Exception as e:
        print(f'  the system may still autocorrect what you type: {errstr(e)}')
        return False

# %% ../nbs/04_window.ipynb #3858b880
def keep_running_in_dock(on_folder=None, recent=None):
    "Hide the last window rather than quit, and fill the Dock menu. Reopen shows one window. Cmd+Q quits."
    global _on_folder, _on_recent
    try:
        from webview.platforms.cocoa import BrowserView
        _on_folder, _on_recent = on_folder, recent
        BrowserView.WindowDelegate, BrowserView.AppDelegate = _dock_delegates()
        return True
    except Exception as e:
        print(f'  the last window will quit {APP_NAME}: {errstr(e)}')
        return False

# %% ../nbs/04_window.ipynb #5e8d9ba6
#: Everything but the title and the size, so a window opened at launch and one opened an hour
#: later are the same window.
WINDOW_KW = dict(min_size=MIN_SIZE, background_color='#171b20', text_select=True, zoomable=True,
                 easy_drag=False)

# %% ../nbs/04_window.ipynb #829b0615
_api = None

# %% ../nbs/04_window.ipynb #62865c1c
#: Which window is showing which workspace, so a folder already open is raised, not opened twice.
_windows = {}

# %% ../nbs/04_window.ipynb #4553e889
def shell_api():
    "The one `ShellApi` every window shares."
    global _api
    if _api is None: _api = ShellApi()
    return _api

# %% ../nbs/04_window.ipynb #b52f1957
def make_window(title=None, size=None):
    "A window on the splash, waiting for a URL."
    import webview
    w, h = size or window_size()
    STORAGE.mkdir(parents=True, exist_ok=True)
    return webview.create_window(title or APP_NAME, html=splash(title or APP_NAME), width=w, height=h,
                                 js_api=shell_api(), **WINDOW_KW)

# %% ../nbs/04_window.ipynb #48f7ad1a
def off_main_thread(fn, name='kavacha-shell'):
    "Run `fn(arg)` on a thread of its own; `create_window` builds nothing on the main thread."
    def go(arg): threading.Thread(target=fn, args=(arg,), daemon=True, name=name).start()
    return go

# %% ../nbs/04_window.ipynb #926fb8b5
def open_window(url, title=None, key=None, url_wait=90):
    "A window on `url`, raised rather than opened twice when `key` already has one."
    title = title or APP_NAME
    if key and (window := _windows.get(key)) is not None:
        try: window.show()      # cocoa's `show` is a `callAfter`, so any thread may ask
        except Exception as e: print(f'  could not raise the window for {title}: {errstr(e)}')
        return window
    window = make_window(title)
    if key: _windows[key] = window
    _point(window, url, url_wait)
    return window

# %% ../nbs/04_window.ipynb #95dfcc76
def _point(window, url, url_wait=90):
    "Wait for the server, then show the workspace. A window that never answers says so."
    if wait_for_http(url, timeout=url_wait): window.load_url(url)
    else: window.load_html(_unreachable(url))

# %% ../nbs/04_window.ipynb #022366f0
def run_shell(urls, titles=(), url_wait=90, gui=None, icon=None, size=None, on_ready=None,
              on_open_folder=None, keys=(), bar=(), lookup=None, on_action=None, on_recent=None):
    "One native window per workspace URL, until they all close. Blocks, on the main thread."
    ok, why = shell_ready()
    if not ok: raise RuntimeError(why)
    import webview
    urls = list(urls)
    if not urls: raise ValueError('the desktop shell needs at least one workspace URL')
    titles = list(titles) + [''] * (len(urls) - len(titles))
    keys = list(keys) + [None] * (len(urls) - len(keys))
    # Every native caller reaches this on the main thread, and none of them may build a window there.
    open_folder = off_main_thread(on_open_folder, 'kavacha-open-folder') if on_open_folder else None
    shell_api().on_open_folder = open_folder
    if sys.platform == 'darwin':
        quiet_text_substitution()                                   # before a web view can ask
        keep_running_in_dock(open_folder, on_recent)                # before any window takes a delegate
    windows = [make_window(t, size) for t in titles]
    for key, window in zip(keys, windows):
        if key: _windows[key] = window
    if open_folder is not None: watch_open_events(open_folder)
    def load(*_):
        "Once the GUI loop is up: wait for the server, then point each window at it."
        for window, url in zip(windows, urls): _point(window, url, url_wait)
        if on_ready is None: return
        try: on_ready()
        except Exception as e: print(f'  desktop shell: {errstr(e)}')
    # One list, shared: pywebview rebuilds the bar whenever the focused window's menu is not the
    # one it built last, and a window opened for a folder later has no menu of its own.
    built = menus(bar, lookup, on_action) if bar else []
    webview.start(load, gui=gui or why, debug=bool(os.environ.get(f'{ENV_PREFIX}WEBVIEW_DEBUG')),
                  private_mode=False, storage_path=str(STORAGE), icon=icon, menu=built)

# %% ../nbs/04_window.ipynb #e20b82a4
def menus(bar, lookup, on_action, run=None):
    "The menu bar for `bar`, or an empty one off macOS. Its own function so a test can build one."
    if sys.platform != 'darwin': return []
    try:
        import webview
        webview.settings['SHOW_DEFAULT_MENUS'] = False   # ours are in the order macOS expects
        built, specs = menu_bar(bar, lookup, on_action, run)
        install_menu_patch(specs, lookup)
        return built
    except Exception as e:
        print(f'  no menu bar: {errstr(e)}')
        return []

# %% ../nbs/04_window.ipynb #8d4390c0
def watch_open_events(on_folder):
    "Answer the `odoc` Apple Event Finder sends a running app. macOS only, best-effort."
    if sys.platform != 'darwin': return None
    try: from Foundation import NSAppleEventManager, NSURL
    except ImportError: return None
    def code(s): return int.from_bytes(s.encode(), 'big')
    def handle(event, _reply):
        try:
            items = event.paramDescriptorForKeyword_(code('----'))
            for i in range(1, (items.numberOfItems() or 0) + 1):
                url = items.descriptorAtIndex_(i).stringValue()
                if not url: continue
                p = NSURL.URLWithString_(url).path() if url.startswith('file:') else url
                if p and os.path.isdir(str(p)): on_folder(str(p))
        except Exception as e: print(f'  open-folder event: {errstr(e)}')
    try:
        mgr = NSAppleEventManager.sharedAppleEventManager()
        mgr.setEventHandler_andSelector_forEventClass_andEventID_(
            _OpenHandler.alloc().init_with(handle), b'handleEvent:reply:',
            code('aevt'), code('odoc'))
        return handle
    except Exception as e:
        print(f'  could not register the open-folder handler: {errstr(e)}')
        return None

# %% ../nbs/04_window.ipynb #43f5f496
try:                                     # pragma: no cover - macOS only
    import objc
    from Foundation import NSObject
    class _RecentTarget(NSObject):
        "What a Dock menu row fires at. `objc.super`, as `_OpenHandler` needs for the same reason."
        def init_with(self, fn):
            self = objc.super(_RecentTarget, self).init()
            if self is None: return None
            self._fn = fn
            return self
        def openRecent_(self, sender):
            path = sender.representedObject()
            if self._fn and path: self._fn(str(path))

    class _OpenHandler(NSObject):
        "An Apple Event handler must be a selector on an Objective-C object."
        def init_with(self, fn):
            # `objc.super`, not `super()`: the builtin has no `init` to find on an ObjC class, so
            # registration raised and nothing opened a folder dropped on the Dock or picked in Finder.
            self = objc.super(_OpenHandler, self).init()
            if self is None: return None
            self._fn = fn
            return self
        def handleEvent_reply_(self, event, reply): self._fn(event, reply)
except Exception:                        # pragma: no cover - everywhere else
    _OpenHandler = _RecentTarget = None


# The Mac menu bar. pywebview builds it; what is added here is the ordering, the chords it has no
# support for, and the rows AppKit implements itself. See `docs/desktop.md`.

# %% ../nbs/04_window.ipynb #2abce1db
CMD, CTRL, ALT, SHIFT = 1 << 20, 1 << 18, 1 << 19, 1 << 17

# %% ../nbs/04_window.ipynb #67b7600e
_MODS = {'mod': CMD, 'cmd': CMD, 'ctrl': CTRL, 'alt': ALT, 'opt': ALT, 'shift': SHIFT,
         'hyper': CMD | CTRL | ALT | SHIFT}

# %% ../nbs/04_window.ipynb #fc6e894d
#: AppKit spells these as private-use unichars, not as their names.
_NAMED = {'up': '', 'down': '', 'left': '', 'right': '',
          'pageup': '', 'pagedown': '', 'home': '', 'end': '',
          'delete': '', 'enter': '\r', 'return': '\r', 'tab': '\t', 'space': ' ',
          'backspace': '\x08', 'escape': '\x1b'}

# %% ../nbs/04_window.ipynb #accc4c25
def mac_key(chord):
    "`(keyEquivalent, modifierMask)` for one chord, or None when AppKit cannot spell it."
    parts = str(chord or '').split()[0].split('+') if chord else []
    if not parts or not parts[-1]: return None
    mask, base = 0, parts[-1]
    for p in parts[:-1]:
        if (m := _MODS.get(p.lower())) is None: return None
        mask |= m
    if len(base) == 1 and base.isupper(): mask |= SHIFT
    base = _NAMED.get(base.lower(), base.lower())
    if len(base) != 1: return None
    return base, mask

# %% ../nbs/04_window.ipynb #73585946
def menu_chord(action, lookup):
    """The chord to put on a menu row, or None to leave it bare.

    A key equivalent is consulted before the keystroke reaches the web view, so anything installed
    here is taken away from the page. Only a global action with a modifier is safe: a scoped one
    would fire outside its scope, and a bare letter would fire while you were typing it.
    """
    k = lookup(action)
    if k is None or not k.bound or k.scope != 'global': return None
    first = k.keys[0]
    if not (set(first.split('+')[:-1]) & {'mod', 'cmd', 'ctrl', 'alt', 'opt', 'hyper'}): return None
    return mac_key(first)

# %% ../nbs/04_window.ipynb #a6757b5e
def _title(row, lookup):
    "The label for an action row: the keymap's, or the action with its underscores opened up."
    k = lookup(row.action)
    t = (k.label if k and k.label else row.action.replace('_', ' '))
    return t[:1].upper() + t[1:]

# %% ../nbs/04_window.ipynb #923d6167
def menu_bar(bar, lookup, on_action, run=None):
    "pywebview menus for `bar`, plus the table `_decorate` needs to finish them off AppKit-side."
    from webview.menu import Menu, MenuAction, MenuSeparator
    run = run or _menu_run
    menus, specs = [], {}
    for title, rows in bar:
        items = []
        for row in rows:
            if isinstance(row, MenuItem) and not row.action: items.append(MenuSeparator()); continue
            if isinstance(row, Std):
                specs[(title, row.title)] = row
                items.append(MenuAction(row.title, lambda: None))
            elif isinstance(row, Js):
                items.append(MenuAction(row.title, (lambda e: lambda: run(e))(row.expr)))
            else:
                name = _title(row, lookup)
                specs[(title, name)] = row
                items.append(MenuAction(name, (lambda a: lambda: on_action(a))(row.action)))
        menus.append(Menu(title, items))
    return menus, specs

# %% ../nbs/04_window.ipynb #6b12e1dd
def eval_js(js):
    "Run one expression in the window that has focus, and return what it evaluated to."
    import webview
    if (window := webview.active_window()) is None: return None
    try: return window.evaluate_js(js)
    except Exception as e:
        print(f'  menu: {errstr(e)}')
        return None

_menu_run = eval_js   #: the name the menu bar called it by

# %% ../nbs/04_window.ipynb #9dcda4ff
_menu_patched = False

# %% ../nbs/04_window.ipynb #a505d335
def install_menu_patch(specs, lookup):
    """Finish each item off as AppKit needs it, wherever pywebview builds the bar.

    It rebuilds on every focus change to a window whose menu differs, so anything done once to the
    bar after start is thrown away. This wraps the one method both rebuild paths go through.
    """
    global _menu_patched
    if _menu_patched: return False
    try:
        from webview.platforms.cocoa import BrowserView
    except Exception as e:
        print(f'  no menu bar: {errstr(e)}')
        return False
    original = BrowserView._recreate_menus
    def recreate(self, user_menu):
        main = original(self, user_menu)
        try: _decorate(main, specs, lookup)
        except Exception as e: print(f'  menu bar: {errstr(e)}')
        return main
    BrowserView._recreate_menus = recreate
    _menu_patched = True
    return True

# %% ../nbs/04_window.ipynb #e6ab65e8
def _decorate(main, specs, lookup):
    "Chords onto the rows that may have one, and the responder chain onto the rows AppKit owns."
    import AppKit
    for i in range(main.numberOfItems()):
        sub = main.itemAtIndex_(i).submenu()
        if sub is None: continue
        title = str(sub.title())
        for j in range(sub.numberOfItems()):
            item = sub.itemAtIndex_(j)
            spec = specs.get((title, str(item.title())))
            if spec is None: continue
            if isinstance(spec, Std):
                item.setTarget_(None)          # nil target is what walks the responder chain
                item.setAction_(spec.selector)
                got = mac_key(f'{spec.mods}+{spec.key}') if spec.key else None
            else: got = menu_chord(spec.action, lookup)
            if got: item.setKeyEquivalent_(got[0]); item.setKeyEquivalentModifierMask_(got[1])
        if title == 'Window': AppKit.NSApp().setWindowsMenu_(sub)
